# Generated by Django 4.1.2 on 2022-10-15 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("post", models.TextField()),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Kategoriya nomi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
                "ordering": ["title", "id"],
            },
        ),
        migrations.CreateModel(
            name="Katalog",
            fields=[
                (
                    "okpo",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="okpo raqami"
                    ),
                ),
                ("soato", models.IntegerField(verbose_name="Hudud kodi")),
                ("name", models.CharField(max_length=50, verbose_name="Korxona nomi")),
                (
                    "biznes",
                    models.BooleanField(default=False, verbose_name="Kichik biznes"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menyu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Asosiy menyu"
                    ),
                ),
                ("turi", models.CharField(max_length=2, verbose_name="Menyu turi")),
            ],
            options={
                "verbose_name": "Menyu",
                "verbose_name_plural": "Menyular",
                "ordering": ["title", "turi"],
            },
        ),
        migrations.CreateModel(
            name="Ekologiya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Sarlavxa")),
                ("content", models.TextField(blank=True, verbose_name="Kontent")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kiritilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Uzgartirilgan sana"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="photos/%y/%m/%d/", verbose_name="Rasm"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Qushilgan"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sayt.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yangilik",
                "verbose_name_plural": "Yangiliklar",
                "ordering": ["-created_at", "id"],
            },
        ),
    ]
