# Generated by Django 4.1.2 on 2022-10-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sayt", "0002_menyuasosiy"),
    ]

    operations = [
        migrations.DeleteModel(name="Menyuasosiy",),
    ]
