# Generated by Django 4.1.2 on 2022-10-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sayt", "0004_news"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ekologiya",
            options={
                "ordering": ["-created_at", "id"],
                "verbose_name": "Ekologiya",
                "verbose_name_plural": "Ekologiyalar",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-created_at", "content"],
                "verbose_name": "Yangilik",
                "verbose_name_plural": "Yangiliklar",
            },
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(blank=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Kiritilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Ruxsat berilgan"),
        ),
        migrations.AlterField(
            model_name="news",
            name="photo",
            field=models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name="Rasm"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Sarlavxa"),
        ),
        migrations.AlterField(
            model_name="news",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="O'zgartirilgan sana"
            ),
        ),
    ]
