# Generated by Django 4.1.2 on 2022-10-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sayt", "0005_alter_ekologiya_options_alter_news_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title"],
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
            },
        ),
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sayt.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                db_index=True, max_length=150, verbose_name="Kategotiya nomi"
            ),
        ),
    ]
