# Generated by Django 4.1.2 on 2022-10-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sayt", "0006_alter_category_options_news_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sayt.category",
                verbose_name="Kategoriyasining nomi",
            ),
        ),
    ]
